---
language: cpp

sudo: required

compiler:
- gcc
- clang

os: linux

install:
- sudo dpkg -i libboost1.55*.deb
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get install -y libuchardet0 libuchardet-dev
- sudo apt-get install -y libboost1.55*
- sudo apt-get install -y g++-5
  
script:
- export CC=gcc-5
- export CXX=g++-5
- sh scripts/deploy.sh

branch:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
    - chat.freenode.net#xiyoulinux
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
