---
language: cpp

sudo: required

compiler:
- gcc
- clang

os: linux

install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update
- sudo apt-get install -y mpi-default-dev libicu-dev python-dev python3-dev libbz2-dev zlib1g-dev openssl catch
- sudo apt-get install -y libuchardet0 libuchardet-dev
- sudo apt-get install -y g++-5
# install boost
- wget --no-verbose --output-document=boost-trunk.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2/download
- export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
- mkdir -p $BOOST_ROOT
- tar jxf boost-trunk.tar.bz2 --strip-components=1 -C $BOOST_ROOT
- (cd $BOOST_ROOT; ./bootstrap.sh --with-libraries=system,thread)
- (cd $BOOST_ROOT; sudo ./b2 threading=multi -d0 install)
  
script:
- export CC=gcc-5
- export CXX=g++-5
- sh scripts/deploy.sh

branch:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
    - chat.freenode.net#xiyoulinux
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
